---
- name: Testar conexão com vCenter
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  vars_files:
    - vars.yml

  tasks:
    - name: Obter datacenters no vCenter
      vmware_datacenter_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: resultado

    - name: Mostrar resultado
      debug:
        var: resultado.datacenter_info

